In [11]:
!pip install pandas numpy scikit-learn matplotlib seaborn

Requirement already satisfied: pandas in /opt/conda/lib/python3.11/site-packages (2.3.3)
Requirement already satisfied: numpy in /opt/conda/lib/python3.11/site-packages (1.26.4)
Requirement already satisfied: scikit-learn in /opt/conda/lib/python3.11/site-packages (1.7.2)
Requirement already satisfied: matplotlib in /opt/conda/lib/python3.11/site-packages (3.10.8)
Requirement already satisfied: seaborn in /opt/conda/lib/python3.11/site-packages (0.13.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/conda/lib/python3.11/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/conda/lib/python3.11/site-packages (from pandas) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /opt/conda/lib/python3.11/site-packages (from pandas) (2025.3)
Requirement already satisfied: scipy>=1.8.0 in /opt/conda/lib/python3.11/site-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /opt/conda/lib/python3.11/site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /opt/conda/lib/python3.11/site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: contourpy>=1.0.1 in /opt/conda/lib/python3.11/site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /opt/conda/lib/python3.11/site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /opt/conda/lib/python3.11/site-packages (from matplotlib) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /opt/conda/lib/python3.11/site-packages (from matplotlib) (1.4.9)
Requirement already satisfied: packaging>=20.0 in /opt/conda/lib/python3.11/site-packages (from matplotlib) (24.2)
Requirement already satisfied: pillow>=8 in /opt/conda/lib/python3.11/site-packages (from matplotlib) (11.3.0)
Requirement already satisfied: pyparsing>=3 in /opt/conda/lib/python3.11/site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [12]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

In [13]:
# Load red wine data
red_url = "https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv"
red = pd.read_csv(red_url, sep=';')

# Load white wine data
white_url = "https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-white.csv"
white = pd.read_csv(white_url, sep=';')

print("Red wine shape:", red.shape)
print("White wine shape:", white.shape)

Red wine shape: (1599, 12)
White wine shape: (4898, 12)

In [14]:
# add wine type column
red['type'] = 0
white['type'] = 1

# combine datasets
wine = pd.concat([red, white], ignore_index=True)

wine.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,type
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,0
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5,0
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5,0
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6,0
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,0

In [15]:
X = wine.drop("quality", axis=1)
y = wine["quality"]

# split data
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print(X_train.shape, X_test.shape)

(5197, 12) (1300, 12)

In [16]:
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [17]:
y_pred = model.predict(X_test)

rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2 = r2_score(y_test, y_pred)

print("RMSE:", rmse)
print("R² Score:", r2)

RMSE: 0.735689101706392
R² Score: 0.267157485126273

In [18]:
import joblib

joblib.dump(model, "wine_quality_model.pkl")
print("Model saved!")

Model saved!

In [19]:
coefficients = pd.DataFrame({
    "Feature": X.columns,
    "Coefficient": model.coef_
}).sort_values(by="Coefficient", ascending=False)

coefficients

                 Feature  Coefficient
9              sulphates     0.763015
8                     pH     0.527633
10               alcohol     0.232594
0          fixed acidity     0.092133
3         residual sugar     0.062822
5    free sulfur dioxide     0.005978
6   total sulfur dioxide    -0.001632
2            citric acid    -0.097888
11                  type    -0.335208
4              chlorides    -0.582632
1       volatile acidity    -1.508810
7                density  -102.081690

In [20]:
sample = X_test.iloc[0:1]
prediction = model.predict(sample)

print("Predicted Quality:", prediction[0])
print("Actual Quality:", y_test.iloc[0])

Predicted Quality: 6.693327284423347
Actual Quality: 8

In [21]:
wine.to_csv("wine_combined.csv", index=False)

In [2]:
import sagemaker
from sagemaker.sklearn.estimator import SKLearn

role = sagemaker.get_execution_role()

estimator = SKLearn(
    entry_point="train_sagemaker.py",
    source_dir="/home/sagemaker-user/sm_job",
    role=role,
    instance_type="ml.m5.large",
    framework_version="1.2-1",
    py_version="py3",
)

estimator.fit()

sagemaker.config INFO - Applied value from config key = SageMaker.PythonSDK.Modules.Session.DefaultS3Bucket
sagemaker.config INFO - Applied value from config key = SageMaker.PythonSDK.Modules.Session.DefaultS3ObjectKeyPrefix
sagemaker.config INFO - Applied value from config key = SageMaker.PythonSDK.Modules.Session.DefaultS3Bucket
sagemaker.config INFO - Applied value from config key = SageMaker.PythonSDK.Modules.Session.DefaultS3ObjectKeyPrefix
sagemaker.config INFO - Applied value from config key = SageMaker.TrainingJob.Environment
2026-02-23 02:21:12 Starting - Starting the training job...
2026-02-23 02:21:28 Starting - Preparing the instances for training...
2026-02-23 02:22:15 Downloading - Downloading the training image......../miniconda3/lib/python3.9/site-packages/sagemaker_containers/_server.py:22: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
2026-02-23 02:23:22,838 sagemaker-containers INFO     Imported framework sagemaker_sklearn_container.training
2026-02-23 02:23:22,842 sagemaker-training-toolkit INFO     No GPUs detected (normal if no gpus installed)
2026-02-23 02:23:22,845 sagemaker-training-toolkit INFO     No Neurons detected (normal if no neurons installed)
2026-02-23 02:23:22,861 sagemaker_sklearn_container.training INFO     Invoking user training script.
2026-02-23 02:23:23,250 sagemaker-training-toolkit INFO     No GPUs detected (normal if no gpus installed)
2026-02-23 02:23:23,253 sagemaker-training-toolkit INFO     No Neurons detected (normal if no neurons installed)
2026-02-23 02:23:23,271 sagemaker-training-toolkit INFO     No GPUs detected (normal if no gpus installed)
2026-02-23 02:23:23,274 sagemaker-training-toolkit INFO     No Neurons detected (normal if no neurons installed)
2026-02-23 02:23:23,290 sagemaker-training-toolkit INFO     No GPUs detected (normal if no gpus installed)
2026-02-23 02:23:23,293 sagemaker-training-toolkit INFO     No Neurons detected (normal if no neurons installed)
2026-02-23 02:23:23,308 sagemaker-training-toolkit INFO     Invoking user script
Training Env:
{
    "additional_framework_parameters": {},
    "channel_input_dirs": {},
    "current_host": "algo-1",
    "current_instance_group": "homogeneousCluster",
    "current_instance_group_hosts": [
        "algo-1"
    ],
    "current_instance_type": "ml.m5.large",
    "distribution_hosts": [],
    "distribution_instance_groups": [],
    "framework_module": "sagemaker_sklearn_container.training:main",
    "hosts": [
        "algo-1"
    ],
    "hyperparameters": {},
    "input_config_dir": "/opt/ml/input/config",
    "input_data_config": {},
    "input_dir": "/opt/ml/input",
    "instance_groups": [
        "homogeneousCluster"
    ],
    "instance_groups_dict": {
        "homogeneousCluster": {
            "instance_group_name": "homogeneousCluster",
            "instance_type": "ml.m5.large",
            "hosts": [
                "algo-1"
            ]
        }
    },
    "is_hetero": false,
    "is_master": true,
    "is_modelparallel_enabled": null,
    "is_smddpmprun_installed": false,
    "is_smddprun_installed": false,
    "job_name": "sagemaker-scikit-learn-2026-02-23-02-21-09-855",
    "log_level": 20,
    "master_hostname": "algo-1",
    "model_dir": "/opt/ml/model",
    "module_dir": "s3://amazon-sagemaker-913524921725-us-east-1-cp292gcmooo3l3/shared/sagemaker-scikit-learn-2026-02-23-02-21-09-855/source/sourcedir.tar.gz",
    "module_name": "train_sagemaker",
    "network_interface_name": "eth0",
    "num_cpus": 2,
    "num_gpus": 0,
    "num_neurons": 0,
    "output_data_dir": "/opt/ml/output/data",
    "output_dir": "/opt/ml/output",
    "output_intermediate_dir": "/opt/ml/output/intermediate",
    "resource_config": {
        "current_host": "algo-1",
        "current_instance_type": "ml.m5.large",
        "current_group_name": "homogeneousCluster",
        "hosts": [
            "algo-1"
        ],
        "instance_groups": [
            {
                "instance_group_name": "homogeneousCluster",
                "instance_type": "ml.m5.large",
                "hosts": [
                    "algo-1"
                ]
            }
        ],
        "network_interface_name": "eth0",
        "topology": null
    },
    "user_entry_point": "train_sagemaker.py"
}
Environment variables:
SM_HOSTS=["algo-1"]
SM_NETWORK_INTERFACE_NAME=eth0
SM_HPS={}
SM_USER_ENTRY_POINT=train_sagemaker.py
SM_FRAMEWORK_PARAMS={}
SM_RESOURCE_CONFIG={"current_group_name":"homogeneousCluster","current_host":"algo-1","current_instance_type":"ml.m5.large","hosts":["algo-1"],"instance_groups":[{"hosts":["algo-1"],"instance_group_name":"homogeneousCluster","instance_type":"ml.m5.large"}],"network_interface_name":"eth0","topology":null}
SM_INPUT_DATA_CONFIG={}
SM_OUTPUT_DATA_DIR=/opt/ml/output/data
SM_CHANNELS=[]
SM_CURRENT_HOST=algo-1
SM_CURRENT_INSTANCE_TYPE=ml.m5.large
SM_CURRENT_INSTANCE_GROUP=homogeneousCluster
SM_CURRENT_INSTANCE_GROUP_HOSTS=["algo-1"]
SM_INSTANCE_GROUPS=["homogeneousCluster"]
SM_INSTANCE_GROUPS_DICT={"homogeneousCluster":{"hosts":["algo-1"],"instance_group_name":"homogeneousCluster","instance_type":"ml.m5.large"}}
SM_DISTRIBUTION_INSTANCE_GROUPS=[]
SM_IS_HETERO=false
SM_MODULE_NAME=train_sagemaker
SM_LOG_LEVEL=20
SM_FRAMEWORK_MODULE=sagemaker_sklearn_container.training:main
SM_INPUT_DIR=/opt/ml/input
SM_INPUT_CONFIG_DIR=/opt/ml/input/config
SM_OUTPUT_DIR=/opt/ml/output
SM_NUM_CPUS=2
SM_NUM_GPUS=0
SM_NUM_NEURONS=0
SM_MODEL_DIR=/opt/ml/model
SM_MODULE_DIR=s3://amazon-sagemaker-913524921725-us-east-1-cp292gcmooo3l3/shared/sagemaker-scikit-learn-2026-02-23-02-21-09-855/source/sourcedir.tar.gz
SM_TRAINING_ENV={"additional_framework_parameters":{},"channel_input_dirs":{},"current_host":"algo-1","current_instance_group":"homogeneousCluster","current_instance_group_hosts":["algo-1"],"current_instance_type":"ml.m5.large","distribution_hosts":[],"distribution_instance_groups":[],"framework_module":"sagemaker_sklearn_container.training:main","hosts":["algo-1"],"hyperparameters":{},"input_config_dir":"/opt/ml/input/config","input_data_config":{},"input_dir":"/opt/ml/input","instance_groups":["homogeneousCluster"],"instance_groups_dict":{"homogeneousCluster":{"hosts":["algo-1"],"instance_group_name":"homogeneousCluster","instance_type":"ml.m5.large"}},"is_hetero":false,"is_master":true,"is_modelparallel_enabled":null,"is_smddpmprun_installed":false,"is_smddprun_installed":false,"job_name":"sagemaker-scikit-learn-2026-02-23-02-21-09-855","log_level":20,"master_hostname":"algo-1","model_dir":"/opt/ml/model","module_dir":"s3://amazon-sagemaker-913524921725-us-east-1-cp292gcmooo3l3/shared/sagemaker-scikit-learn-2026-02-23-02-21-09-855/source/sourcedir.tar.gz","module_name":"train_sagemaker","network_interface_name":"eth0","num_cpus":2,"num_gpus":0,"num_neurons":0,"output_data_dir":"/opt/ml/output/data","output_dir":"/opt/ml/output","output_intermediate_dir":"/opt/ml/output/intermediate","resource_config":{"current_group_name":"homogeneousCluster","current_host":"algo-1","current_instance_type":"ml.m5.large","hosts":["algo-1"],"instance_groups":[{"hosts":["algo-1"],"instance_group_name":"homogeneousCluster","instance_type":"ml.m5.large"}],"network_interface_name":"eth0","topology":null},"user_entry_point":"train_sagemaker.py"}
SM_USER_ARGS=[]
SM_OUTPUT_INTERMEDIATE_DIR=/opt/ml/output/intermediate
PYTHONPATH=/opt/ml/code:/miniconda3/bin:/miniconda3/lib/python39.zip:/miniconda3/lib/python3.9:/miniconda3/lib/python3.9/lib-dynload:/miniconda3/lib/python3.9/site-packages:/miniconda3/lib/python3.9/site-packages/setuptools/_vendor
Invoking script with the following command:
/miniconda3/bin/python train_sagemaker.py
2026-02-23 02:23:23,309 sagemaker-training-toolkit INFO     Exceptions not imported for SageMaker Debugger as it is not installed.
2026-02-23 02:23:23,309 sagemaker-training-toolkit INFO     Exceptions not imported for SageMaker TF as Tensorflow is not installed.
RMSE: 0.7357
R2: 0.2672
Saved model + metrics for SageMaker container run.
2026-02-23 02:23:25,201 sagemaker-containers INFO     Reporting training SUCCESS

2026-02-23 02:23:44 Training - Training image download completed. Training in progress.
2026-02-23 02:23:44 Uploading - Uploading generated training model
2026-02-23 02:23:44 Completed - Training job completed
Training seconds: 114
Billable seconds: 114